// Regenera lib/data/item_list_generated.dart desde items_extra_data_complete.txt
//
//   dart run tool/generate_item_list.dart
import 'dart:convert';
import 'dart:io';

const _itemsPath = 'assets/tsvFiles/items_extra_data_complete.txt';
const _outPath = 'lib/data/item_list_generated.dart';

void main() {
  final file = File(_itemsPath);
  if (!file.existsSync()) {
    stderr.writeln('No existe $_itemsPath');
    exitCode = 1;
    return;
  }

  final names = <String>{};
  for (final line in file.readAsLinesSync(encoding: latin1)) {
    if (line.trim().isEmpty) continue;
    final parts = line.split('\t');
    if (parts.length < 5) continue;
    final name = parts[4].trim();
    if (name.isEmpty) continue;
    names.add(name);
  }

  final sorted = names.toList()..sort();
  final buf = StringBuffer()
    ..writeln('// GENERATED by tool/generate_item_list.dart — no editar a mano')
    ..writeln('List<String> itemList = [');
  for (final n in sorted) {
    buf.writeln('  ${jsonEncode(n)},');
  }
  buf.writeln('];');

  File(_outPath).writeAsStringSync(buf.toString());
  stdout.writeln('${sorted.length} nombres → $_outPath');
}
